[workspace]
resolver = "2"
members = [
  "chain-reorg",
  "chaindexing",
  "chaindexing-diesel",
  "chaindexing-tests",
  "chains",
  "config",
  "contracts",
  "events",
  "events-ingester",
  "nodes",
  "repos"
]